- name: Darkrock Ventures
  id: 1
  description: This is a wonderful game. Please buy it.
  box-image-filename: darkrock-ventures-box.png
  closeup-image-filename: darkrock-ventures-closeup.png
  price: $44.99
  min-players: 2
  max-players: 5
  ages: 12 and up
  weight: 500
  link-to-rules: http://magicmeeplegames.com
  link-to-facebook: http://magicmeeplegames.com
  link-to-bgg: http://magicmeeplegames.com

- name: Overworld
  id: 04
  description: This is where you type the text of another description.
  box-image-filename: Overworld-box-image-500px.png
  closeup-image-filename: overworld-closeup.png
  price: $34.99
  min-players: 1
  max-players: 4
  ages: 12 and up
  weight: 300
  link-to-rules: http://magicmeeplegames.com
  link-to-facebook: http://magicmeeplegames.com
  link-to-bgg: http://magicmeeplegames.com
