- name: Darkrock Ventures
  product-code: MMG001
  designer: Michael Eskue
  developer: Andrew Enriquez, Ian Stedman
  artist: Naomi Robinson
  graphic-designer: Darrell Louder, Ian Stedman
  publisher: Magic Meeple Games & Gamelyn Games
  ages-official: 14+
  ages-community: 12+
  min-players: 1
  max-players: 5
  solo-mode: true
  cooperative-mode: true
  competitive-mode: true
  play-time: 30-45 (mins)
  setup-time: 10 (mins)
  teach-learn-time: 15 (mins)
  complexity: 2.4 (out of 5)
  short-description: A worker placement game about mining and exporting in hostile outer-space. Players will control a mining company working in harsh conditions to acquire the most credits to win.
  long-description: Competitive worker-placement meets clever dice-manipulation. Take control of your own asteroid mining company and compete to extract the most minerals for the most cash before the asteroid is depleted. Also, you're all under constant assault by alien marauders! Includes Solo and Co-Op variant expansions.
  box-image: darkrock-ventures-box-500px.png
  game-contents-image: 500px_Darkrock-ventures-closeup.jpg
  closeup-front-image: DRV_Box_Face.png
  closeup-back-image: DRV_Box_Back.png
  original-msrp: 49.99
  current-msrp: 45.99
  weight: 1000g
  wholesale-price: 22.50
  case-quantity: 10
  expansions-included:  All Kickstarter Stretch Goals, Solo/Co-operative Variant, 2-Player Variant, Research Deck
  expansions-sold-separately: Darkrock Ventures Expansion Pack #1
  availability: Now available
  available: true
  link-to-rules: https://boardgamegeek.com/filepage/118140/darkrock-ventures-official-rulebook
  link-to-bgg: https://boardgamegeek.com/boardgame/166418/darkrock-ventures
  link-to-kickstarter: https://www.kickstarter.com/projects/magicmeeplegames/darkrock-ventures-asteroid-mining-in-deep-space-bo

- name: "Darkrock Ventures Expansion Pack #1"
  product-code: MMG001a
  designer: Michael Eskue
  developer: Ian Stedman
  artist: Naomi Robinson
  graphic-designer: Darrell Louder, Ian Stedman
  publisher: Magic Meeple Games & Gamelyn Games
  ages-official: no change
  ages-community: no change
  players: no change
  play-time: no change
  setup-time: no change
  teach-learn-time: no change
  complexity: no change
  short-descripton: "Adds ten (10) additional cards to expand the <em>Darkrock Ventures</em> base game. (Requires <em>Darkrock Ventures</em> base game to play)"
  long-description: "<em>Darkrock Ventures Expansion Pack #1</em> includes an additional ten cards: 5 new Research Cards and 5 new Corporate Sponsors cards. They can be included into any game mode in <em>Darkrock Ventures</em> that uses these cards! (Not a stand-alone game. Requires <em>Darkrock Ventures</em> base game to play.)"
  box-image-filename: 500px_DRVExpPack1.jpg
  game-contents-image: 500px_DRV_ExpPack1Contents.jpg, DRV_ExpPack1Contents.jpg
  closeup-front-image: DRV_ExpPack1_CoverCard_Front.jpg
  closeup-back-image: n/a
  original-msrp: 4.99
  current-msrp: 4.99
  weight: 21g
  wholesale-price: 2.50
  case-qty: n/a
  expands: Darkrock Ventures
  availability: Now available
  available: true
  link-to-rules: https://boardgamegeek.com/filepage/118140/darkrock-ventures-official-rulebook
  link-to-bgg: https://boardgamegeek.com/boardgameexpansion/208856/darkrock-ventures-expansion-pack-1
  link-to-kickstarter: https://www.kickstarter.com/projects/magicmeeplegames/darkrock-ventures-asteroid-mining-in-deep-space-bo

- name: Fire of Eidolon
  product-code: MMG101
  designer: Michael Lipton
  developer: Ian Stedman, Trish Stedman, Katie Lipton
  artist: Brandi York, Andreas Propst, Ian Stedman
  graphic-designer: Mary Trehern, Ian Stedman
  publisher: Magic Meeple Games
  ages-official: 14+
  ages-community: 10+
  min-players: 1
  max-players: 6
  solo-mode: true
  cooperative-mode: true
  competitive-mode: false
  play-time: 30-45 (mins)
  setup-time: 5 (mins)
  teach-learn-time: 10 (mins)
  complexity: 1.9 (out of 5)
  short-description: This quick-playing, diceless, co-operative dungeon crawl for 1-6 players is like a romp through classic 1990s video games! Explore the dungeon, collect the tokens of power, and escape with the Fire of Eidolon before the dungeon is destroyed around you by the evil agents of Vorax!
  long-description: The Fire of Eidolon is the quintessential source of light magic in your world and it has been stolen by the agents of the Dark Sorcerer, a being of untold power and horror who intends to bury it forever in the very same void that imprisons him, even if that means sealing you inside with it! It is up to you and your band of brave Heroes to recover the Fire of Eidolon and extract it from the dark void Dungeon before its arcane light is extinguished forever. Your quest is to search through the Dungeon before you, Challenge the horrors inside for their trophies, and Break the three Dark Relics sealing the Fire to reclaim it...and then you have to escape. Are you up to the challenge?
  box-image: fire-of-eidolon-box-image-500px.png
  game-contents-image: FoE_contentsphoto.jpg
  closeup-front-image: FoE_Box_Face.jpg
  closeup-back-image: FoE_Box_Back.jpg
  original-msrp: 34.99
  current-msrp: 34.99
  weight: 653g
  wholesale-price: 17.50
  case-quantity: 10
  expansions-included:  All Kickstarter Stretch Goals, Advanced Heroes (6), Scenario Quests (4), Warp Zone tiles Add-on
  expansions-sold-seperately: coming soon
  availability: Now available
  link-to-rules: https://boardgamegeek.com/filepage/151678/fire-eidolon-official-rulebook
  link-to-bgg: https://boardgamegeek.com/boardgame/190333/fire-eidolon
  link-to-kickstarter: https://www.kickstarter.com/projects/magicmeeplegames/fire-of-eidolon-16-bit-inspired-co-op-dungeon-boar
  available: true

- name: Overworld
  product-code: MMG201
  designer: Nemo Rathwald
  developer: Ian Stedman
  artist: Jeff Perryman, Matt Arnold, Ian Stedman
  graphic-designer: Matt Arnold, Ian Stedman
  publisher: Magic Meeple Games
  ages-official: 14+
#  ages-community: TBA
  min-players: 1
  max-players: 4 (5 with Add-on)
  solo-mode: true
  cooperative-mode: false
  competitive-mode: true
  play-time: 30-40 (mins)
  setup-time: 5 (mins)
  teach-learn-time: 15 (mins)
#  complexity: TBA
  short-description: Strategic, diceless, tile placement/area control game for 1-4 with a retro videogame flair, all in a super-portable package!
  long-description: In every classic JRPG, the heroes encountered a mysterious stranger, who gave them a map to a dungeon, and stocked them with potions, keys, and other provisions. But how was the map drawn? How did the wise stranger learn of all these dire warnings? In Overworld, you are the hero's mysterious mentor. All those years before you sent the hero to the underworld, you mapped the Overworld! By laying tiles, you will seek to claim regions of Forests or Mountains with your Bird meeples, and regions of Reefs or Whirlpools with your Ship meeples. When the tiles form a hole in the world, the player who explored the most tiles there will place a Dungeon Door meeple into the hole. Can you foresee uncertain spots in the geography, indeterminate in the distance? Will you uncover a dungeon... or wander the repeating pixel textures forever?
  box-image: Overworld-box-image-500px.png
  game-contents-image: OVW_ppc_contents.jpg
  closeup-front-image: OVW_Box_Face.jpg
  closeup-back-image: OVW_Box_Back.jpg
  original-msrp: 39.99
  current-msrp: 39.99
  weight: TBA
  wholesale-price: 20.00
  case-quantity: TBA
  expansions-included:  Airship Tile, Provisions Expansion, Towns Expansion, Solo Quest Mode
  expansions-sold-seperately: Summoners (5th Player) Expansion
  availability: Shipping Soon
  available: false
  link-to-rules: https://boardgamegeek.com/filepage/162519/overworld-rulebook-optimized
  link-to-bgg: https://boardgamegeek.com/boardgame/220843/overworld
  link-to-kickstarter: https://www.kickstarter.com/projects/magicmeeplegames/overworld-16-bit-tile-placement-and-exploration-bo

- name: Overworld Summoners 5th Player Expansion
  product-code: MMG201a
  designer: Nemo Rathwald
  developer: Ian Stedman
  artist: Jeff Perryman, Matt Arnold, Ian Stedman
  graphic-designer: Matt Arnold, Ian Stedman
  publisher: Magic Meeple Games
  ages-official: no change
  ages-community: TBA
  players: 1-5
  solo-mode: true
  cooperative-mode: semi-cooperative
  competitive-mode: true
  play-time: +10 Minutes
  setup-time: no change
  teach-learn-time: +10 Minutes
  complexity: Small increase from base game
  short-description: AKA "5th Player Add-on" Expand your <em>Overworld</em> experience with playing pieces to add a 5th player to the game, as well as new tiles and tokens for the <em>Summoners</em> game variant! (Base game required to play)
  long-description: <em>Overworld Summoners</em> expands the base game to 5 players with additional tiles and tokens to facilitate ALL of the additional rules found in the booklet, including the <em>Summoners</em> variant! Also introduces Desert and Glacier regions to the game!
#  box-image-filename: TBA
#  game-contents-image: TBA
#  closeup-front-image: TBA
#  closeup-back-image: TBA
  original-msrp: 9.99
  current-msrp: 9.99
  weight: TBA
  wholesale-price: 5.00
  case-quantity: TBA
  expands: Overworld
  availability: Shipping Soon
  available: false
  link-to-rules: https://boardgamegeek.com/filepage/162519/overworld-rulebook-optimized
  link-to-bgg: TBA
  link-to-kickstarter: https://www.kickstarter.com/projects/magicmeeplegames/overworld-16-bit-tile-placement-and-exploration-bo
  
