- name: Darkrock Ventures
  id: 1
  description: This is a wonderful game. Please buy it.
  box-image-filename: darkrock-ventures-box.png
  closeup-image-filename: darkrock-ventures-closeup.png
  price: $44.99
  min-players: 2
  max-players: 5
  ages: 12 and up
  weight: 500
  link-to-rules: http://magicmeeplegames.com
  link-to-facebook: http://magicmeeplegames.com
  link-to-bgg: http://magicmeeplegames.com
  snes: false
  availability: In Stock

- name: Darkrock Ventures Expansion Pack
  id: 2
  description: Description text goes here.
  box-image-filename: darkrock-ventures-expansion-pack-box-image-500px.png
  closeup-image-filename: darkrock-ventures-expansion-pack-closeup.png
  price: $4.99
  min-players: 2
  max-players: 5
  ages: 12 and up
  weight: 60
  link-to-rules: http://magicmeeplegames.com
  link-to-facebook: http://magicmeeplegames.com
  link-to-bgg: http://magicmeeplegames.com
  snes: false
  availability: In Stock

- name: Fire Of Eidolon
  id: 3
  description: These descriptive blurbs will probably be one or two sentences in length.
  box-image-filename: fire-of-eidolon-box-image-500px.png
  closeup-image-filename: overworld-closeup.png
  price: $34.99
  min-players: 1
  max-players: 6
  ages: 12 and up
  weight: 300
  link-to-rules: http://magicmeeplegames.com
  link-to-facebook: http://magicmeeplegames.com
  link-to-bgg: http://magicmeeplegames.com
  snes: true
  availability: In Stock

- name: Overworld
  id: 4
  description: This is where you type the text of another description.
  box-image-filename: Overworld-box-image-500px.png
  closeup-image-filename: overworld-closeup.png
  price: $34.99
  min-players: 1
  max-players: 4
  ages: 12 and up
  weight: 300
  link-to-rules: http://magicmeeplegames.com
  link-to-facebook: http://magicmeeplegames.com
  link-to-bgg: http://magicmeeplegames.com
  snes: true
  availability: Coming Soon
